name: Default Branch

on:
  push:
    branches:
    - main

jobs:
  test-master:
    runs-on: elisa-normal
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Run lint
      run: mage go:lint

    - name: Run test
      run: mage go:unitTest

    - name: Upload test coverage to codecov
      uses: codecov/codecov-action@v5
      with:
        url: https://codecov.csf.elisa.fi
        use_oidc: true

  build-packages:
    runs-on: elisa-normal
    timeout-minutes: 30
    needs: test-master
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Build packages
      run: mage go:crossBuild

    - name: Notify failure
      if: failure()
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_TEXT: "${{ github.repository }} release [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }}) build failed."
      run: send-to-mattermost
